// GENERATED by kg/src/emit.ts from kg/src/l1.ts + kg/src/vocab.ts. Do not edit: change the Zod source and run `npm run build` in kg/.
ValueSet: KGDerivationVS
Title: "Knowledge graph: derivation"
Description: "All codes of KGDerivation."

* ^experimental = false
* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* include codes from system KGDerivation
