// GENERATED by kg/src/emit.ts from kg/src/l1.ts + kg/src/vocab.ts. Do not edit: change the Zod source and run `npm run build` in kg/.
ValueSet: KGGradeStrengthVS
Title: "Knowledge graph: GRADE recommendation strength"
Description: "All codes of KGGradeStrength."

* ^experimental = false
* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* include codes from system KGGradeStrength
