// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
ValueSet: KGInterventionTypeVS
Title: "Knowledge graph L1: intervention type"
Description: "All codes of KGInterventionType."

* ^experimental = false
* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* include codes from system KGInterventionType
