// GENERATED by kg/src/emit.ts from kg/src/l1.ts + kg/src/vocab.ts. Do not edit: change the Zod source and run `npm run build` in kg/.
ValueSet: KGL1ClassesVS
Title: "Knowledge graph L1: classes"
Description: "All codes of KGL1Classes."

* ^experimental = false
* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* include codes from system KGL1Classes
