// GENERATED by kg/src/emit.ts from kg/src/l1-library.ts (the library extension). Do not edit: change the Zod source and run `npm run build` in kg/.
ValueSet: KGL1LibraryPredicatesVS
Title: "Knowledge graph L1Library: predicates"
Description: "All codes of KGL1LibraryPredicates."

* ^experimental = false
* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* include codes from system KGL1LibraryPredicates
