// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
ValueSet: KGOutcomeImportanceVS
Title: "Knowledge graph L1: outcome importance"
Description: "All codes of KGOutcomeImportance."

* ^experimental = false
* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* include codes from system KGOutcomeImportance
