// GENERATED by kg/src/emit.ts from kg/src/l1.ts + kg/src/vocab.ts. Do not edit: change the Zod source and run `npm run build` in kg/.
ValueSet: KGResolutionStatusVS
Title: "Knowledge graph: resolution status"
Description: "All codes of KGResolutionStatus."

* ^experimental = false
* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* include codes from system KGResolutionStatus
