// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
ValueSet: KGRecommendationStrengthVS
Title: "Knowledge graph L1: recommendation strength"
Description: "All codes of KGRecommendationStrength."

* ^experimental = false
* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* include codes from system KGRecommendationStrength
