// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
ValueSet: KGTerminologySystemVS
Title: "Knowledge graph L1: terminology system"
Description: "All codes of KGTerminologySystem."

* ^experimental = false
* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* include codes from system KGTerminologySystem
