// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGCertainty
Title: "Knowledge graph L1: certainty"
Description: "GRADE certainty of evidence. The 2014 handbook calls it quality of evidence and names certainty as a synonym (§9.1). Rated per outcome on evidence; the overall certainty on a recommendation is the lowest across its critical outcomes (§9.6). Source: smart-kg ontology/l1/l1.json valueSets \"certainty\"; WHO handbook for guideline development (2014) §9.1, §9.5–9.6."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #high "High" "Very confident the true effect lies close to the estimate."
* #moderate "Moderate" "Moderately confident; the true effect is likely close to the estimate but may be substantially different."
* #low "Low" "Limited confidence; the true effect may be substantially different."
* #very-low "Very low" "Very little confidence; the true effect is likely substantially different. Not the same as no evidence — that is kind no-recommendation."
