// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGChangeStatus
Title: "Knowledge graph L1: change status"
Description: "Whether this edition of a consolidated guideline introduces, updates or carries a recommendation or indicator unchanged. Printed as NEW / UPDATE tags. Source: smart-kg ontology/l1/l1.json valueSets \"change-status\"; Consolidated guidelines on person-centred HIV strategic information (2022), summary recommendations; handbook §1.7.2."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #new "New" "Introduced in this edition."
* #updated "Updated" "Changed in this edition."
* #unchanged "Unchanged" "Carried from an earlier edition without change."
