// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGCitationKind
Title: "Knowledge graph L1: citation kind"
Description: "Whether a citation string names a source, or stands in for one that is missing. Source: smart-kg ontology/l1/l1.json valueSets \"citation-kind\"; IMMZ DAK indicators workbook: '[Add appropriate reference]'."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #reference "Reference" "Names a source."
* #placeholder "Placeholder" "The author's marker that a source is still to be added. Never resolves; counted as a coverage gap."
