// GENERATED by kg/src/emit.ts from kg/src/l1.ts + kg/src/vocab.ts. Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGDerivation
Title: "Knowledge graph: derivation"
Description: "How a node or edge of a SMART Guidelines knowledge graph came to be. Every node and edge is exactly one of the three, and `decided` is the one a reviewer needs to find. Source: smart-kg shapes/recommendation-graph.schema.json $defs.derivation."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #derived "Derived" "Mechanically produced, no choice involved."
* #inferred "Inferred" "A rule that could reasonably have gone another way."
* #decided "Decided" "The source is silent and someone chose."
