// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGElementType
Title: "Knowledge graph L1: element type"
Description: "What kind of printed block a publication element is. Source: smart-kg ontology/l1/l1.json valueSets \"element-type\"; Observed in the ANC and HIV SI guidelines and the immunization summary tables."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #table "Table" "A table, with columns and rows."
* #table-row "Table row" "One row of a table."
* #footnote "Footnote" "A footnote attached to a row or a block."
* #figure "Figure" "A figure."
* #chart "Chart" "A chart; its data stays with its source."
* #image "Image" "An image."
* #flowchart "Flowchart" "A flowchart or algorithm; its steps are modelled at L2, not here."
* #box "Box" "A boxed panel."
* #list "List" "A list set apart on the page."
