// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGEvidenceType
Title: "Knowledge graph L1: evidence type"
Description: "Which kind of evidence a row is, and so which scale its certainty is on: GRADE for effects, GRADE-CERQual for qualitative findings. Source: smart-kg ontology/l1/l1.json valueSets \"evidence-type\"; ANC guideline (2016) methods (GRADE and GRADE-CERQual)."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #effect "Effect" "Quantitative effect estimate; certainty is GRADE."
* #qualitative "Qualitative" "Qualitative finding; certainty is GRADE-CERQual confidence."
* #resource-use "Resource use" "Costs or resource requirements."
* #other "Other" "Any other kind."
