// GENERATED by kg/src/emit.ts from kg/src/l1.ts + kg/src/vocab.ts. Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGGradeStrength
Title: "Knowledge graph: GRADE recommendation strength"
Description: "How strongly a recommendation is made. Strength is NOT certainty: a strong recommendation can rest on low-certainty evidence and a conditional one on high certainty. Moved from smart-kg/methodologies/grade.md by bean wg7r, 2026-09-24 (owner: 'needs to be part of skill/SKOS'). Read with the `grade` skill. Source: folio-assistant cat-harness/code-lists/grade-recommendation-strength.json (bean wg7r), codes and definitions verbatim; Andrews JC, et al. GRADE guidelines: 15. Going from evidence to recommendation — determinants of a recommendation's direction and strength. J Clin Epidemiol 2013;66(7):726-735; WHO Handbook for Guideline Development, 2nd ed. (2014), which uses 'conditional' for GRADE's 'weak' <https://doi.org/10.1016/j.jclinepi.2013.02.003>."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #strong "Strong" "The guideline panel is confident that the desirable effects of following the recommendation clearly outweigh the undesirable effects — or clearly do not, for a recommendation against — so most informed people would choose the recommended course."
* #conditional "Conditional" "The desirable effects probably outweigh the undesirable effects, but the panel is less confident: the balance is close, the evidence uncertain, or values and preferences vary, so different choices will suit different people or settings. GRADE's 'weak'; WHO uses 'conditional'."
