// GENERATED by kg/src/emit.ts from kg/src/l1.ts + kg/src/vocab.ts. Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGGradeCertainty
Title: "Knowledge graph: GRADE certainty of evidence"
Description: "The four levels of certainty GRADE assigns to a BODY of evidence for one outcome — never to a single citation. Randomised trials start at high and observational studies at low, before rating down or up. Moved from smart-kg/methodologies/grade.md by bean wg7r, 2026-09-24 (owner: 'needs to be part of skill/SKOS'). Read with the `grade` skill. Source: folio-assistant cat-harness/code-lists/grade-certainty.json (bean wg7r), codes and definitions verbatim; Balshem H, et al. GRADE guidelines: 3. Rating the quality of evidence. J Clin Epidemiol 2011;64(4):401-406 <https://doi.org/10.1016/j.jclinepi.2010.07.015>."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #high "High" "We are very confident that the true effect lies close to the estimate of the effect."
* #moderate "Moderate" "We are moderately confident in the effect estimate: the true effect is likely to be close to it, but there is a possibility that it is substantially different."
* #low "Low" "Our confidence in the effect estimate is limited: the true effect may be substantially different from it."
* #very-low "Very low" "We have very little confidence in the effect estimate: the true effect is likely to be substantially different from it. Not the same finding as 'could not determine' — absent evidence is a gap, not a grade."
