// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGGrcStatus
Title: "Knowledge graph L1: grc status"
Description: "Whether the Guideline Review Committee approved the publication. All WHO publications containing recommendations must be approved (handbook §1.10.1); a consolidated guideline whose recommendations were all previously approved and unchanged does not require review (§1.7.2). Absent means not recorded — not the same as not reviewed. Source: smart-kg ontology/l1/l1.json valueSets \"grc-status\"; WHO handbook for guideline development (2014), §1.7.2, §1.10.1."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #approved "Approved" "Approved by the GRC."
* #not-required "Not required" "GRC review was not required — a §1.9 product, or a consolidation of previously approved, unchanged recommendations."
* #not-reviewed "Not reviewed" "Contains recommendations and was not reviewed by the GRC — including those published before the GRC was established in 2007, which the handbook says should be updated (§12.5.2)."
