// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGIdentifierType
Title: "Knowledge graph L1: identifier type"
Description: "Which kind of identifier a publication carries. The first available, in this order, builds the publication IRI. url comes last: a web address is the least stable identifier and is used only for sources that have no other. Source: smart-kg ontology/l1/l1.json valueSets \"identifier-type\"; WHO IRIS practice; CDHIv2.fsh carries an ISBN."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #isbn "Isbn" "ISBN-13, electronic version preferred."
* #iris-handle "Iris handle" "WHO IRIS handle, e.g. 10665/250796."
* #doi "Doi" "Digital Object Identifier."
* #issn "Issn" "ISSN, for serials such as the Weekly Epidemiological Record."
* #url "Url" "The canonical web address of a WHO source published only on the web, such as the routine immunization summary tables or the UHC Compendium. Used for the IRI only when no isbn, iris-handle, doi or issn exists; scheme, query and trailing slash are dropped. A moved page is a new publication, linked to the old one by supersedes."
* #other "Other" "Any other identifier; never used to build an IRI."
