// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGInterventionType
Title: "Knowledge graph L1: intervention type"
Description: "DRAFT. What kind of intervention a recommendation or catalogued intervention concerns. To be aligned with the UHC Compendium's categories once checked. Source: smart-kg ontology/l1/l1.json valueSets \"intervention-type\"; WHO handbook §1.7.1 (clinical, health system, public health, diagnostic, surveillance); digital interventions per CDHI."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #medicine "Medicine" "A medicine or supplement."
* #vaccine "Vaccine" "A vaccine."
* #diagnostic "Diagnostic" "A test or screening."
* #procedure "Procedure" "A clinical procedure."
* #device-product "Device product" "A device or commodity."
* #behavioural "Behavioural" "Counselling, education or behaviour change."
* #public-health "Public health" "A population-level public health measure."
* #health-system "Health system" "Service delivery, workforce or financing."
* #health-information "Health information" "Data collection, monitoring or surveillance."
* #digital "Digital" "A digital health intervention, classified by CDHI."
