// GENERATED by kg/src/emit.ts from kg/src/l1-library.ts (the library extension). Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGL1LibraryPredicates
Title: "Knowledge graph L1Library: predicates"
Description: "The predicates of the L1Library layer. An edge's `predicate` is one of these; which (source, target) pairs each licenses is the layer's edge table. Source: kg/src/l1-library.ts (migrated from smart-kg ontology/l1-library/l1-library.json)."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #specializationOf "specializationOf" "An L1 layout node to the library node it specialises: the same printed thing, with L1's more specific aspects. Upstream only."
