// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGL1Predicates
Title: "Knowledge graph L1: predicates"
Description: "The predicates of the L1 layer. An edge's `predicate` is one of these; which (source, target) pairs each licenses is the layer's edge table. Source: kg/src/L1.ts (migrated from smart-kg ontology/L1/L1.json)."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #contains "contains" "Layout containment only: publication, sections, elements. It never points at content."
* #hasSupplement "hasSupplement" "A guideline to its web annex or supplementary document (handbook §12.1)."
* #supersedes "supersedes" "This replaces that, between publications and between individual recommendations (handbook §1.7.2, §12.5; ANC Table 1 footnotes)."
* #refines "refines" "A recommendation narrows or conditions another."
* #partOf "partOf" "A sub-recommendation a), b) to its parent. Each part carries its own change status (HIV SI 2022)."
* #definedIn "definedIn" "The one publication that issued this content: its authority."
* #presentedIn "presentedIn" "A place this content is printed, in any publication. Many per node. Restatement is presentedIn into a publication other than definedIn. The edge carries renderedText only when the printed wording differs from the stored text."
* #answers "answers" "A recommendation answers a key question. Many-to-many (handbook §7.4)."
* #addresses "addresses" "A row of an evidence profile addresses a key question."
* #hasOutcome "hasOutcome" "A key question names an outcome. A list shared by several questions is one set of outcome nodes."
* #forOutcome "forOutcome" "An evidence row grades one outcome. Optional: qualitative evidence may concern a criterion such as values."
* #aboutIntervention "aboutIntervention" "The I of a key question, joined to a catalogued intervention."
* #supportedBy "supportedBy" "A recommendation to the evidence it rests on."
* #hasRemark "hasRemark" "A recommendation to a remark: definition, implementation, precaution, contraindication, subgroup, research gap or training."
* #recommends "recommends" "A recommendation concerns a catalogued intervention. Optional: only when the mapping is known."
* #measures "measures" "What an indicator counts: a catalogued intervention, or adherence to a recommendation (handbook Table 10.2)."
* #justifiedBy "justifiedBy" "Why an indicator exists: the recommendation its rationale cites (HIV SI 2022, PRV.3)."
* #crossReferences "crossReferences" "Names an external code. Records that a code was cited, never what it means. Terminology is a leaf."
* #classifiedAs "classifiedAs" "Placement of a catalogued intervention in UHC, ICHI or CDHI."
* #numberedAs "numberedAs" "A citation's '(n)' to row n of the same artefact's reference list. Mechanical."
* #resolvesTo "resolvesTo" "What a citation or reference entry refers to, as precisely as the string allows. Matching is a judgement: inferred, or decided when a person chose between candidates."
