// GENERATED by kg/src/emit.ts from kg/src/l1-library.ts (the library extension). Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGL1LibraryClasses
Title: "Knowledge graph L1Library: classes"
Description: "The classes of the L1Library layer of the SMART Guidelines knowledge graph. A node's `type` is one of these. Source: kg/src/l1-library.ts (migrated from smart-kg ontology/l1-library/l1-library.json)."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #library-node "Library node" "A node in the ingested library L1 is read from: a source document, a section or a block, addressed by the library's own IRI. Opaque, as L1 asserts nothing about the library's internal model; the library is upstream, so pointing at it keeps the layering rule."
