// GENERATED by kg/src/emit.ts from kg/src/l1.ts + kg/src/vocab.ts. Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGL1Predicates
Title: "Knowledge graph L1: predicates"
Description: "The predicates of the L1 layer. An edge's `predicate` is one of these; which (source, target) pairs each licenses is the layer's edge table. Source: kg/src/L1.ts (migrated from smart-kg ontology/L1/L1.json)."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #contains "contains" "Structural containment. A publication contains sections; a section contains recommendations."
* #supersedes "supersedes" "This publication replaces that one. Guideline updates are the reason impact analysis matters."
* #refines "refines" "A recommendation narrows or conditions another, rather than replacing it."
* #hasPopulation "hasPopulation" "PICO."
* #hasIntervention "hasIntervention" "PICO."
* #hasComparator "hasComparator" "PICO."
* #hasOutcome "hasOutcome" "PICO."
* #supportedBy "supportedBy" "Recommendation to its body of evidence, carrying GRADE certainty."
* #hasRemark "hasRemark" "Implementation consideration. Often the part a DAK author actually acts on."
* #recommends "recommends" "A recommendation is about a health intervention. The hinge to L2."
* #definedIn "definedIn" "A schedule or indicator is normatively defined in a publication."
* #schedules "schedules" "A schedule entry prescribes when an intervention is delivered."
* #measures "measures" "An indicator measures delivery of an intervention."
* #derivedFrom "derivedFrom" "This normative content restates or operationalises that recommendation."
* #crossReferences "crossReferences" "Names an external code. THE ONLY edge into terminology: it records that a code was cited, never what the code means. See the terminology-code class."
* #classifiedAs "classifiedAs" "Placement in a WHO classification — CDHI for interventions. Also a cross-reference, kept separate because classification is an assertion about the thing, not a mention of a code."
* #appearsIn "appearsIn" "A citation string appears in an L2 or L3 artefact at a stated location."
* #resolvesTo "resolvesTo" "A citation string resolves to a publication or a recommendation. Almost always `inferred` or `decided`, never `derived` — matching a free-text citation is a judgement."
* #implementedBy "implementedBy" "L1 content is implemented by an L2 or L3 artefact, addressed by canonical URL. The graph does not model the target's structure."
