// GENERATED by kg/src/emit.ts from kg/src/l1.ts + kg/src/vocab.ts. Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGL1Classes
Title: "Knowledge graph L1: classes"
Description: "The classes of the L1 layer of the SMART Guidelines knowledge graph. A node's `type` is one of these. Source: kg/src/L1.ts (migrated from smart-kg ontology/L1/L1.json)."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #publication "Publication" "A WHO normative publication: a guideline, guidance, recommendation summary, or classification. Metadata follows Dublin Core, which HealthInterventions already uses."
* #publication-section "Publication section" "A chapter, annex or numbered section. Recommendations are located by section and page, which is what makes an extraction checkable."
* #recommendation "Recommendation" "The atomic normative statement. This is the node nothing in the WHO estate currently makes addressable."
* #remark "Remark" "An implementation consideration attached to a recommendation. Grounded: the BCG table's first annotationEntry carries exactly this — \"Neonates born to women of unknown HIV status should be vaccinated as the benefits…\" — clinical nuance that shapes the decision logic but is not the recommendation itself."
* #evidence "Evidence" "The body of evidence behind a recommendation, with its GRADE certainty rating."
* #population "Population" "PICO P."
* #intervention "Intervention" "PICO I. The clinical or public-health action, distinct from health-intervention, which is the DAK-facing component."
* #comparator "Comparator" "PICO C. Frequently absent in WHO recommendations; absence is recorded rather than invented."
* #outcome "Outcome" "PICO O."
* #health-intervention "Health intervention" "What a recommendation is about, and the hinge to L2. Corresponds to the DAK component smart-base defines as HealthInterventions — today `id`, `description[x]` and `reference 1..* DublinCore`, i.e. a bibliographic citation with no recommendation behind it. This class is what that citation should resolve to."
* #schedule "Schedule" "A normative delivery schedule. Grounded: the BCG table cites \"WHO recommendations for routine immunization – summary tables\", which IS a schedule publication — the single most-cited L1 source in the immunization DAK."
* #schedule-entry "Schedule entry" "One row of a schedule: which intervention, for whom, when, how many doses. This is the granularity a decision table actually consumes — the BCG rules turn on dose count, age and interval since a live vaccine."
* #indicator "Indicator" "A programme indicator defined normatively at L1. Distinct from the DAK's ProgramIndicator component, which is its L2 expression; that model already carries `references 0..* id` pointing at health intervention ids."
* #terminology-code "Terminology code" "A code in an external terminology — ICD-10, ICD-11, SNOMED CT, ATC, or a WHO classification such as CDHI. CROSS-REFERENCE ONLY. It records system, code and display, and asserts NOTHING about the terminology: no hierarchy, no subsumption, no synonyms, no post-coordination. The terminology has its own authority, its own release cycle and its own tooling, and a partial copy here would be wrong within one release. Resolve meaning against the terminology server, not against this graph."
* #citation "Citation" "A citation string exactly as it appears in an L2 or L3 artefact, together with what it was resolved to. Grounded directly in the BCG table, where every rule's annotationEntry[1] reads \"WHO recommendations for routine immunization – summary tables (March 2023) (1)\" — a citation that no tool can currently follow. This class is where that string becomes a link, and where the fact that resolving it was a judgement gets recorded."
* #external-artifact "External artefact" "An L2 or L3 artefact addressed by canonical URL — a BPMN process, a DMN decision table, a FHIR PlanDefinition. Deliberately opaque: it carries an IRI and a free-text kind, and this graph asserts nothing about its internal structure. That opacity is the boundary. The L2 and L3 subgraphs model those artefacts properly; L1 only needs to point."
