// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGOutcomeImportance
Title: "Knowledge graph L1: outcome importance"
Description: "How the guideline development group rated an outcome on the 1–9 scale: 7–9 critical, 4–6 important. Unimportant outcomes are not carried into evidence profiles, so they have no code here. Source: smart-kg ontology/l1/l1.json valueSets \"outcome-importance\"; WHO handbook for guideline development (2014) §7.6, Fig. 7.1."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #critical "Critical" "Rated 7–9: critical for decision-making. Only critical outcomes determine overall certainty."
* #important "Important" "Rated 4–6: important but not critical for decision-making."
