// GENERATED by kg/src/emit.ts from kg/src/l1.ts + kg/src/vocab.ts. Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGPublicationType
Title: "Knowledge graph: publication type"
Description: "What kind of normative publication an L1 publication is. A summary table restates recommendations made elsewhere, and conflating it with a guideline makes provenance wrong. A publication that is none of these (a data portal, a reporting form) leaves the property unset rather than being forced into one. Source: smart-kg ontology/l1/l1.json class publication note ('a guideline, guidance, recommendation summary, or classification') and propertyNote."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #guideline "Guideline" "A normative WHO guideline: it makes recommendations."
* #guidance "Guidance" "Guidance that operationalises recommendations without making new ones."
* #summary-table "Summary table" "A summary that restates recommendations made elsewhere."
* #classification "Classification" "A classification, such as the Classification of Digital Health Interventions."
