// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGPublicationType
Title: "Knowledge graph L1: publication type"
Description: "What kind of publication this is. The distinction that matters most for provenance is guideline versus not: a summary table or position paper restates recommendations made elsewhere, and a §1.9 product makes none of its own. Conflating them makes a citation resolve to the wrong authority. Source: smart-kg ontology/l1/l1.json valueSets \"publication-type\"; WHO handbook for guideline development (2014), Table 1.2 and §1.7–1.9; the BCG decision table's citation for summary-table; CDHIv2.fsh for classification."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #standard-guideline "Standard guideline" "Recommendations on a specific topic or condition, usually new. Most WHO guidelines. Handbook §1.7.1."
* #consolidated-guideline "Consolidated guideline" "Aggregates existing recommendations on a disease or condition, evaluated as up to date; may add new ones. Existing recommendations must be explicitly cross-referenced. Handbook §1.7.2."
* #interim-guideline "Interim guideline" "Guidance when data are incomplete and more are expected; short shelf-life, states when an update is anticipated. Handbook §1.7.3."
* #rapid-advice-guideline "Rapid advice guideline" "Produced in one to three months in a public health emergency, with a review-by date. Handbook §1.7.4, chapter 11."
* #emergency-guideline "Emergency guideline" "Rapid response guidance within hours to days; may rest on expert opinion only. Handbook §1.7.4."
* #collaborative-guideline "Collaborative guideline" "Developed with one or more external organizations sharing the remit. Handbook §1.8.1."
* #external-guideline "External guideline" "Developed by an external organization and adopted by WHO. Handbook §1.8.2."
* #adapted-guideline "Adapted guideline" "An existing WHO guideline adapted to a local context by a Member State. Handbook §1.8.3, §13.1."
* #position-paper "Position paper" "A WHO position paper — for vaccines, the SAGE-reviewed statement of WHO's position published in the Weekly Epidemiological Record. States recommendations; the immunization summary tables are drawn from these."
* #summary-table "Summary table" "A tabular restatement of recommendations made in other publications — e.g. \"WHO recommendations for routine immunization – summary tables\". Cite-worthy, but not the originating authority: a citation resolving here should normally be followed on to the recommendation it restates."
* #classification "Classification" "A WHO classification, such as the Classification of Digital Health Interventions (CDHI). Its codes are cross-referenced through terminology-code, never modelled here."
* #implementation-guidance "Implementation guidance" "An operational manual, implementation guide or tool based on approved guidelines — a \"how to\" document. Makes no recommendations of its own. Handbook §1.9. A DAK is one of these."
* #methodology "Methodology" "A document describing how guidance is produced — the guideline development handbook itself. Handbook §1.9 (standard operating procedures)."
* #supplement "Supplement" "A web annex or supplementary document of another publication, typically holding systematic reviews, GRADE evidence profiles and evidence-to-decision tables. Handbook §12.1. Reached by hasSupplement."
