// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGRecommendationStatus
Title: "Knowledge graph L1: recommendation status"
Description: "Whether a recommendation is still in force. Recommendations in one guideline go out of date at different times (§1.7.2), and a department that doubts a recommendation's validity should say so before the update is done (§12.5.4). This is what impact analysis filters on. Source: smart-kg ontology/l1/l1.json valueSets \"recommendation-status\"; WHO handbook for guideline development (2014) §1.7.2, §12.5."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #current "Current" "In force."
* #under-review "Under review" "Flagged as possibly out of date, with an update planned. Handbook §12.5.4."
* #superseded "Superseded" "Replaced by another recommendation, reached by supersedes."
* #withdrawn "Withdrawn" "Withdrawn without replacement."
