// GENERATED by kg/src/emit.ts from kg/src/l1.ts + kg/src/vocab.ts. Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGResolutionStatus
Title: "Knowledge graph: resolution status"
Description: "Whether a citation string, or a cross-format join, was matched to the thing it names. `ambiguous` is a legitimate terminal state and must not be collapsed to `resolved`. Source: smart-kg ontology/l1/l1.json class citation propertyNote; tools/validate.mjs RESOLVABLE."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #unresolved "Unresolved" "Not matched to anything. The honest default."
* #resolved "Resolved" "Matched to exactly one target, with evidence for the match."
* #ambiguous "Ambiguous" "More than one target fits and none can be preferred from the source."
