// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGRemarkType
Title: "Knowledge graph L1: remark type"
Description: "What a remark is for. Grounded in the six remarks attached to ANC recommendation A.1.1. Source: smart-kg ontology/l1/l1.json valueSets \"remark-type\"; ANC guideline (2016) p. 15; handbook §10.6, §10.8."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #definition "Definition" "Defines a term used in the recommendation."
* #implementation "Implementation" "How to put the recommendation into practice."
* #precaution "Precaution" "A caution to observe when applying it."
* #contraindication "Contraindication" "When the intervention must not be given."
* #subgroup "Subgroup" "Guidance specific to a subgroup."
* #research-gap "Research gap" "Evidence the guideline group says is still needed (handbook §10.8)."
* #training "Training" "A training or capacity need."
