// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGRecommendationStrength
Title: "Knowledge graph L1: recommendation strength"
Description: "GRADE strength. Strength is not certainty: a strong recommendation can rest on low-certainty evidence and a conditional one on high. Record \"weak\" as conditional; the handbook treats them as synonyms (§10.4). Source: smart-kg ontology/l1/l1.json valueSets \"recommendation-strength\"; WHO handbook for guideline development (2014) §10.4."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #strong "Strong" "The desirable effects of adherence clearly outweigh the undesirable. Handbook §10.4.1."
* #conditional "Conditional" "Less certain about the balance of benefits and harms; generally states the conditions under which to implement. Also called weak. Handbook §10.4.2."
