// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGRecommendationKind
Title: "Knowledge graph L1: recommendation kind"
Description: "What sort of normative statement this is. Grading is optional: ANC 2016 prints a direction ('Recommended', 'Not recommended') and no GRADE strength. A strength always needs a direction. A good practice statement and a no-recommendation carry no strength or certainty, and a no-recommendation carries no direction. Source: smart-kg ontology/l1/l1.json valueSets \"recommendation-kind\"; WHO handbook §10.4, §10.7; ANC guideline (2016) Table 1, verified; Guyatt et al. 2016 on good practice statements."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #recommendation "Recommendation" "A graded recommendation, with a direction and a strength. Handbook §10.4."
* #context-specific "Context specific" "Recommended only in specified contexts or settings, stated in the recommendation. ANC guideline (2016) Table 1, verified."
* #research-context "Research context" "Recommended only in the context of rigorous research. ANC guideline (2016) Table 1, verified."
* #good-practice-statement "Good practice statement" "An ungraded statement whose benefit is so clear that grading the evidence is not a useful exercise. Carries no strength or certainty. Guyatt et al. 2016."
* #no-recommendation "No recommendation" "\"No recommendation can be made because…\" — the guideline development group decided the evidence could not support one. Handbook §10.7. Distinct from very-low certainty: absent evidence and weak evidence are different findings."
