// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGResolutionStatus
Title: "Knowledge graph L1: resolution status"
Description: "Whether a citation string has been matched to what it cites. `ambiguous` is a legitimate terminal state — two publications with similar titles is a question for a person — and must not be collapsed to resolved. Source: smart-kg ontology/l1/l1.json valueSets \"resolution-status\"; docs/SCOPE.md."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #unresolved "Unresolved" "Not yet matched."
* #resolved "Resolved" "Matched; a resolvesTo edge says to what."
* #ambiguous "Ambiguous" "More than one candidate, and choosing is a judgement for a person."
