// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGRecommendationDirection
Title: "Knowledge graph L1: recommendation direction"
Description: "For or against. The handbook prefers \"we recommend against X\" to \"X is not recommended\", which is ambiguous between against and no recommendation (§10.6). Source: smart-kg ontology/l1/l1.json valueSets \"recommendation-direction\"; WHO handbook for guideline development (2014) §10.1, §10.6."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #for "For" "The recommendation is in favour of the intervention."
* #against "Against" "The recommendation is against the intervention."
