// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGRowType
Title: "Knowledge graph L1: row type"
Description: "The role of a row within a table. Source: smart-kg ontology/l1/l1.json valueSets \"row-type\"; HIV SI guideline Table 2.3; ANC Table 1."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #header "Header" "A header row, including repeated headers on later pages."
* #group "Group" "A group heading row such as 'A. Nutritional interventions'."
* #data "Data" "A row carrying content."
* #note "Note" "A note row inside the table."
