// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
CodeSystem: KGTerminologySystem
Title: "Knowledge graph L1: terminology system"
Description: "Code systems a DAK is expected to use. An unknown system is a warning, because a misspelt system silently breaks joins across guidelines. Source: smart-kg ontology/l1/l1.json valueSets \"terminology-system\"; smart-base input/fsh/profiles/SGLogicalModel.fsh and Aliases.fsh; UHC Compendium; CDHIv2.fsh."

* ^experimental = false
* ^caseSensitive = true
* ^status = #active
* ^publisher = "World Health Organization (WHO)"

* #SMART "SMART" "SMART Guidelines codes."
* #ICD-11 "ICD 11" "ICD-11."
* #ICF "ICF" "ICF."
* #ICHI "ICHI" "International Classification of Health Interventions."
* #SNOMED-GPS "SNOMED GPS" "SNOMED CT Global Patient Set."
* #ATC "ATC" "Anatomical Therapeutic Chemical classification."
* #UHC "UHC" "UHC Compendium of health interventions."
* #CDHI "CDHI" "Classification of Digital Health Interventions."
