// GENERATED by kg/src/emit.ts from kg/src/l1.ts + kg/src/vocab.ts. Do not edit: change the Zod source and run `npm run build` in kg/.
Logical: KGPublication
Parent: DublinCore
Title: "Knowledge graph L1: Publication"
Description: "A WHO normative publication: a guideline, guidance, recommendation summary, or classification. Metadata follows Dublin Core, which HealthInterventions already uses. publicationType distinguishes normative guideline from guidance from summary table — a summary table restates recommendations made elsewhere, and conflating the two makes provenance wrong. identifier holds ISBN/ISSN/DOI, as CDHIv2 already does. sha256 pins the PDF. Derives from DublinCore (smart-base input/fsh/models/DublinCore.fsh); title, creator, publisher, date, identifier, language, rights are its elements. Class IRI: http://smart.who.int/kg/publication."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* version 0..1 string "Version" "Edition or version, as printed."
* url 0..1 uri "URL" "Where the publication is published."
* sha256 0..1 string "SHA-256" "Hash of the PDF the extraction read; pins the source."
* publicationType 0..1 code "Publication type" "Normative guideline, guidance, summary table or classification. Unset when the publication is none of these."
* publicationType from KGPublicationTypeVS (required)

Logical: KGPublicationSection
Title: "Knowledge graph L1: Publication section"
Description: "A chapter, annex or numbered section. Recommendations are located by section and page, which is what makes an extraction checkable. Class IRI: http://smart.who.int/kg/publication-section."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* heading 0..1 string "Heading" "The section heading, verbatim."
* number 0..1 string "Number" "The section number as printed (\"1.2\", \"Annex 3\")."
* pageRange 0..1 string "Page range" "PDF page or page range the section occupies (\"12-18\")."

Logical: KGRecommendation
Title: "Knowledge graph L1: Recommendation"
Description: "The atomic normative statement. This is the node nothing in the WHO estate currently makes addressable. statement is a VERBATIM quote, never a paraphrase — a paraphrased recommendation is a new recommendation. strength is GRADE (strong | conditional); certainty is GRADE (high | moderate | low | very-low); conditionality records the 'in settings where…' qualifier that decides whether a DAK can adopt it unchanged. Class IRI: http://smart.who.int/kg/recommendation."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* identifier 0..1 string "Identifier" "The recommendation's label or number as printed."
* statement 0..1 markdown "Statement" "The recommendation text, VERBATIM. A paraphrased recommendation is a new recommendation."
* strength 0..1 code "Strength" "GRADE strength, as stated in the source."
* strength from KGGradeStrengthVS (required)
* certainty 0..1 code "Certainty" "GRADE certainty of evidence, as stated in the source."
* certainty from KGGradeCertaintyVS (required)
* conditionality 0..1 string "Conditionality" "The 'in settings where…' qualifier, verbatim, that decides whether a DAK can adopt the recommendation unchanged."
* status 0..1 string "Status" "The recommendation's standing in its publication (for example current or superseded), as stated."

Logical: KGRemark
Title: "Knowledge graph L1: Remark"
Description: "An implementation consideration attached to a recommendation. Grounded: the BCG table's first annotationEntry carries exactly this — \"Neonates born to women of unknown HIV status should be vaccinated as the benefits…\" — clinical nuance that shapes the decision logic but is not the recommendation itself. Class IRI: http://smart.who.int/kg/remark."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* text 0..1 markdown "Text" "The implementation consideration, verbatim."

Logical: KGEvidence
Title: "Knowledge graph L1: Evidence"
Description: "The body of evidence behind a recommendation, with its GRADE certainty rating. Class IRI: http://smart.who.int/kg/evidence."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* summary 0..1 markdown "Summary" "Summary of the body of evidence."
* certainty 0..1 code "Certainty" "GRADE certainty of the body of evidence."
* certainty from KGGradeCertaintyVS (required)
* studyCount 0..1 unsignedInt "Study count" "Number of studies in the body of evidence."
* citation 0..1 string "Citation" "Bibliographic citation of the evidence review."

Logical: KGPopulation
Title: "Knowledge graph L1: Population"
Description: "PICO P. Class IRI: http://smart.who.int/kg/population."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* description 0..1 string "Description" "PICO population, as described in the source."
* ageRange 0..1 string "Age range" "Age range of the population, as stated."
* qualifier 0..1 string "Qualifier" "Further qualification of the population, as stated."

Logical: KGIntervention
Title: "Knowledge graph L1: Intervention"
Description: "PICO I. The clinical or public-health action, distinct from health-intervention, which is the DAK-facing component. Class IRI: http://smart.who.int/kg/intervention."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* description 0..1 string "Description" "PICO intervention, as described in the source."

Logical: KGComparator
Title: "Knowledge graph L1: Comparator"
Description: "PICO C. Frequently absent in WHO recommendations; absence is recorded rather than invented. Class IRI: http://smart.who.int/kg/comparator."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* description 0..1 string "Description" "PICO comparator, as described in the source."

Logical: KGOutcome
Title: "Knowledge graph L1: Outcome"
Description: "PICO O. Class IRI: http://smart.who.int/kg/outcome."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* description 0..1 string "Description" "PICO outcome, as described in the source."

Logical: KGHealthIntervention
Title: "Knowledge graph L1: Health intervention"
Description: "What a recommendation is about, and the hinge to L2. Corresponds to the DAK component smart-base defines as HealthInterventions — today `id`, `description[x]` and `reference 1..* DublinCore`, i.e. a bibliographic citation with no recommendation behind it. This class is what that citation should resolve to. Corresponds to HealthInterventions: identifier = HealthInterventions.id and description = HealthInterventions.description[x]; not a Parent because HealthInterventions requires reference 1..* DublinCore, which in the graph is an edge to a publication rather than a field. Class IRI: http://smart.who.int/kg/health-intervention."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* identifier 0..1 string "Health Intervention ID" "An identifier for the health intervention"
* name 0..1 string "Name" "Name of the health intervention, as listed."
* description 0..1 markdown "Description" "Description of the health intervention"

Logical: KGSchedule
Title: "Knowledge graph L1: Schedule"
Description: "A normative delivery schedule. Grounded: the BCG table cites \"WHO recommendations for routine immunization – summary tables\", which IS a schedule publication — the single most-cited L1 source in the immunization DAK. Class IRI: http://smart.who.int/kg/schedule."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* identifier 0..1 string "Identifier" "Identifier of the schedule, where the source gives one."
* name 0..1 string "Name" "Name of the schedule (a summary table's title)."
* scope 0..1 string "Scope" "Who or what the schedule covers, as stated."

Logical: KGScheduleEntry
Title: "Knowledge graph L1: Schedule entry"
Description: "One row of a schedule: which intervention, for whom, when, how many doses. This is the granularity a decision table actually consumes — the BCG rules turn on dose count, age and interval since a live vaccine. Class IRI: http://smart.who.int/kg/schedule-entry."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* antigen 0..1 string "Antigen" "The antigen or vaccine the row is about."
* doseNumber 0..1 string "Dose number" "Dose in the series as printed (\"1\", \"Booster 1\"). Text, because schedules label boosters rather than count them."
* series 0..1 string "Series" "Primary series or booster series, as stated."
* targetAge 0..1 string "Target age" "Age at which the dose is due, as stated."
* minimumInterval 0..1 string "Minimum interval" "Minimum interval since the previous dose, as stated."
* note 0..1 string "Note" "The row's footnote or remark, verbatim."

Logical: KGIndicator
Title: "Knowledge graph L1: Indicator"
Description: "A programme indicator defined normatively at L1. Distinct from the DAK's ProgramIndicator component, which is its L2 expression; that model already carries `references 0..* id` pointing at health intervention ids. Corresponds to ProgramIndicator: same element names and types (markdown), identifier = ProgramIndicator.id; not a Parent because ProgramIndicator makes name, definition, numerator, denominator and disaggregation 1..1 and an L1 indicator is recorded with what its source states. Class IRI: http://smart.who.int/kg/indicator."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* identifier 0..1 string "Indicator ID" "Identifier for the program indicator"
* name 0..1 string "Name" "Name of the indicator"
* definition 0..1 markdown "Definition" "Definition of what the indicator measures"
* numerator 0..1 markdown "Numerator" "Description of the numerator calculation"
* denominator 0..1 markdown "Denominator" "Description of the denominator calculation"
* disaggregation 0..1 markdown "Disaggregation" "Description of how the indicator should be disaggregated"

Logical: KGTerminologyCode
Parent: Coding
Title: "Knowledge graph L1: Terminology code"
Description: "A code in an external terminology — ICD-10, ICD-11, SNOMED CT, ATC, or a WHO classification such as CDHI. CROSS-REFERENCE ONLY. It records system, code and display, and asserts NOTHING about the terminology: no hierarchy, no subsumption, no synonyms, no post-coordination. The terminology has its own authority, its own release cycle and its own tooling, and a partial copy here would be wrong within one release. Resolve meaning against the terminology server, not against this graph. Derives from Coding (FHIR R4 core datatype); system, code, display, version are its elements. Class IRI: http://smart.who.int/kg/terminology-code."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"

Logical: KGCitation
Title: "Knowledge graph L1: Citation"
Description: "A citation string exactly as it appears in an L2 or L3 artefact, together with what it was resolved to. Grounded directly in the BCG table, where every rule's annotationEntry[1] reads \"WHO recommendations for routine immunization – summary tables (March 2023) (1)\" — a citation that no tool can currently follow. This class is where that string becomes a link, and where the fact that resolving it was a judgement gets recorded. text is verbatim. location is the artefact path plus the element id — e.g. the DMN rule id. numbering preserves the \"(1)\" back-reference into the source document's own bibliography. resolutionStatus is unresolved | resolved | ambiguous; ambiguous is a legitimate terminal state and must not be collapsed to resolved. Class IRI: http://smart.who.int/kg/citation."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* text 0..1 string "Text" "The citation string, VERBATIM as it appears in the citing artefact."
* location 0..1 string "Location" "The citing artefact's path plus the element id (a DMN rule id, a page)."
* numbering 0..1 string "Numbering" "The '(1)' back-reference into the citing document's own bibliography."
* resolutionStatus 0..1 code "Resolution status" "unresolved | resolved | ambiguous. Ambiguous is a legitimate terminal state."
* resolutionStatus from KGResolutionStatusVS (required)

Logical: KGExternalArtifact
Title: "Knowledge graph L1: External artefact"
Description: "An L2 or L3 artefact addressed by canonical URL — a BPMN process, a DMN decision table, a FHIR PlanDefinition. Deliberately opaque: it carries an IRI and a free-text kind, and this graph asserts nothing about its internal structure. That opacity is the boundary. The L2 and L3 subgraphs model those artefacts properly; L1 only needs to point. Class IRI: http://smart.who.int/kg/external-artifact."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* iri 0..1 uri "IRI" "Canonical URL or IRI of the L2 or L3 artefact."
* targetKind 0..1 string "Target kind" "What kind of artefact it is, free text (\"DMN decision table\", \"DAK component\")."
* version 0..1 string "Version" "Version of the artefact, where known."

Logical: KGEvidenceLocation
Title: "Knowledge graph: evidence location"
Description: "Where a node or edge came from in its source. Required on anything not mechanically derived."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* location 1..1 string "Location" "file:line, a spreadsheet sheet and cell, or a BPMN element id."
* quote 0..1 string "Quote" "Verbatim text from the source."
* artifact 0..1 string "Artifact" "The generated artifact affected, where one exists."

Logical: KGProvenanceSource
Title: "Knowledge graph: provenance source"
Description: "A source a graph document was extracted from, pinned by hash."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* path 1..1 string "Path" "Path of the source."
* sha256 1..1 string "SHA-256" "Hash of the source (64 lower-case hex digits)."
* repository 0..1 string "Repository" "Repository holding the source."
* commit 0..1 string "Commit" "Commit the source was read at."
* note 0..1 string "Note" "What the hash covers, where that is not obvious."

Logical: KGNode
Title: "Knowledge graph: node"
Description: "One typed node of a knowledge-graph document. Its instance fields are an instance of the logical model of its class (see definedBy), e.g. KGPublication for a publication."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* id 1..1 string "ID" "IRI, unique within the document."
* type 1..1 code "Type" "The node's class."
* type from KGL1ClassesVS (required)
* label 1..1 string "Label" "Human-readable name. Required so a retrieved node reads without resolving it."
* definedBy 0..1 uri "Defined by" "Canonical URL of the logical model giving this node's instance shape."
* properties 0..1 BackboneElement "Properties" "Instance fields, as declared by the class's logical model."
* derivation 1..1 code "Derivation" "derived | inferred | decided."
* derivation from KGDerivationVS (required)
* note 0..1 string "Note" "Why it is what it is. Required unless derived."
* evidence 0..1 KGEvidenceLocation "Evidence" "Where it came from. Required unless derived."
* flagRef 0..1 string "Flag" "Id of a flag raised while extracting this node."
* skill 0..1 string "Skill" "Skill id that produced this node."

Logical: KGEdge
Title: "Knowledge graph: edge"
Description: "One reified statement: a predicate from a source node to a target node, with its derivation and evidence."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* type 1..1 code "Type" "Always Statement (rdf:Statement)."
* predicate 1..1 code "Predicate" "The predicate; the layer's edge table says which (source, target) pairs it licenses."
* predicate from KGL1PredicatesVS (required)
* source 1..1 string "Source" "IRI of the source node."
* target 1..1 string "Target" "IRI of the target node."
* qualifier 0..1 string "Qualifier" "A label on the relationship."
* derivation 1..1 code "Derivation" "derived | inferred | decided."
* derivation from KGDerivationVS (required)
* note 0..1 string "Note" "Why it is what it is. Required unless derived."
* evidence 0..1 KGEvidenceLocation "Evidence" "Where it came from. Required unless derived."
* flagRef 0..1 string "Flag" "Id of a flag raised while extracting this edge."
* skill 0..1 string "Skill" "Skill id that produced this edge."
* properties 0..1 BackboneElement "Properties" "Fields of the statement itself."
  * resolutionStatus 0..1 code "Resolution status" "For a cross-format join: unresolved | resolved | ambiguous."
  * resolutionStatus from KGResolutionStatusVS (required)
  * matchedOn 0..1 string "Matched on" "What the join was matched on."

Logical: KGGraphDocument
Title: "Knowledge graph L1: graph document"
Description: "One L1 knowledge-graph document: typed nodes and reified edges, provenance-pinned to the sources it was extracted from. In JSON the context element is written @context."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* context 1..1 uri "Context" "The JSON-LD context (written @context in JSON)."
* id 1..1 string "ID" "IRI of this graph document."
* type 1..1 code "Type" "Always Entity (prov:Entity)."
* ontologyVersion 1..1 string "Ontology version" "schemaVersion of the ontology this graph was built against."
* generatedAt 1..1 dateTime "Generated at" "When the document was generated."
* wasDerivedFrom 0..* KGProvenanceSource "Derived from" "The sources this graph was extracted from, each pinned by hash."
* nodes 0..* KGNode "Nodes" "The nodes."
* edges 0..* KGEdge "Edges" "The edges."
* dak 0..1 BackboneElement "DAK" "The DAK envelope: the fields of the DAK logical model."
