// GENERATED by kg/src/emit.ts from kg/src/l1-library.ts (the library extension). Do not edit: change the Zod source and run `npm run build` in kg/.
Logical: KGLibraryNode
Title: "Knowledge graph L1-LIBRARY: Library node"
Description: "A node in the ingested library L1 is read from: a source document, a section or a block, addressed by the library's own IRI. Opaque, as L1 asserts nothing about the library's internal model; the library is upstream, so pointing at it keeps the layering rule. Class IRI: http://smart.who.int/kg/library-node."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* iri 0..1 uri "IRI" "The library node's own IRI."
* libraryClass 0..1 uri "Library class" "The library class it is an instance of (cat-harness:SourceDocument, doco:Section, cat-harness:Block, …)."
* entry 0..1 string "Entry" "The library entry it belongs to (e.g. 9789240016514-eng)."
* pageRange 0..1 string "Page range" "Physical pages it covers, where it is a section or block."
