// GENERATED by kg/src/emit.ts from kg/src/l1.ts (L1 3.0). Do not edit: change the Zod source and run `npm run build` in kg/.
Logical: KGPublication
Parent: DublinCore
Title: "Knowledge graph L1: Publication"
Description: "A WHO publication: a guideline of any of the handbook's types, a position paper, a summary table, a classification, implementation guidance, or a supplement. Metadata follows Dublin Core. identifiers is a list of {type, value}; type is from identifier-type, and the first of isbn, iris-handle, doi, issn, url builds the IRI, so an edition change is a new publication. issued and modified are Dublin Core. reviewBy is the handbook's review-by date (§12.5.1). sha256 pins the PDF. Derives from DublinCore (smart-base input/fsh/models/DublinCore.fsh); title, creator, publisher, language, rights are its elements. Class IRI: http://smart.who.int/kg/publication."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* issued 0..1 date "Issued" "Dublin Core dcterms:issued — date of formal issuance (YYYY, YYYY-MM or YYYY-MM-DD)."
* modified 0..1 date "Modified" "Dublin Core dcterms:modified — date the publication was changed."
* version 0..1 string "Version" "Edition or version, as printed."
* identifiers 0..* BackboneElement "Identifiers" "Typed identifiers; the first of isbn, iris-handle, doi, issn, url builds the IRI."
  * type 0..1 code "Type" "The identifier's kind."
  * type from KGIdentifierTypeVS (required)
  * value 0..1 string "Value" "The identifier, as printed."
* url 0..1 uri "URL" "Where the publication is published."
* sha256 0..1 string "SHA-256" "Hash of the PDF; pins the source."
* publicationType 0..1 code "Publication type" "What kind of publication this is."
* publicationType from KGPublicationTypeVS (required)
* grcStatus 0..1 code "Grc status" "Whether the Guideline Review Committee approved the publication."
* grcStatus from KGGrcStatusVS (required)
* reviewBy 0..1 date "Review by" "The handbook's review-by date (§12.5.1)."

Logical: KGPublicationSection
Title: "Knowledge graph L1: Publication section"
Description: "A chapter, annex or numbered section, at any depth. Class IRI: http://smart.who.int/kg/publication-section."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* heading 0..1 string "Heading" "The section heading, verbatim."
* number 0..1 string "Number" "The section number as printed (\"1.2\", \"Annex 3\")."
* pageRange 0..1 string "Page range" "Pages the section occupies, as printed or physical (\"12-18\")."
* ordinal 0..1 unsignedInt "Ordinal" "Position among its siblings."

Logical: KGPublicationElement
Title: "Knowledge graph L1: Publication element"
Description: "One printed block: a table, a table row, a footnote, a figure, a chart, an image, a flowchart, a box or a list. It records where something is printed and exactly what is printed that no content node holds. It carries no meaning of its own; meaning lives in content nodes, joined by presentedIn. columns is the header text, verbatim. columnMap names, per column, the content field that fills it when the table is re-rendered (e.g. 'Recommendation' -> statement). cells holds only text no content node holds; a cell filled through columnMap is null. text is for unmodelled printed text such as a footnote that is not a remark. sha256 is for images. Class IRI: http://smart.who.int/kg/publication-element."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* elementType 0..1 code "Element type" "What kind of printed block a publication element is."
* elementType from KGElementTypeVS (required)
* label 0..1 string "Label" "The element's printed label (\"Table 3\", \"Box 2\")."
* caption 0..1 markdown "Caption" "The element's caption, verbatim."
* pageRange 0..1 string "Page range" "Pages the element is printed on."
* ordinal 0..1 unsignedInt "Ordinal" "Position among its siblings."
* rowType 0..1 code "Row type" "The role of a row within a table."
* rowType from KGRowTypeVS (required)
* columns 0..* string "Columns" "The header text, verbatim, one per column; a blank header is an empty string."
* columnMap 0..* BackboneElement "Column map" "Per column, the content field that fills it when the table is re-rendered (e.g. 'Recommendation' -> statement)."
  * column 0..1 string "column" "The column."
  * field 0..1 string "field" "The field."
* cells 0..* string "Cells" "Text no content node holds, per column; a cell filled through columnMap is null."
* text 0..1 markdown "Text" "Unmodelled printed text, such as a footnote that is not a remark."
* sha256 0..1 string "SHA-256" "Hash of the image, for an image element."

Logical: KGRecommendation
Title: "Knowledge graph L1: Recommendation"
Description: "A normative statement from a WHO guideline. Kinds other than a graded recommendation (context-specific, research-only, good practice statement, no-recommendation) are the same node with a different kind. statement is verbatim and is the only stored copy. intervention, population, setting, provider and timing are verbatim slots taken from the statement, its remarks, or the enclosing caption or heading. setting absorbs the former conditionality. identifier is the published number (e.g. A.1.1), used in the IRI; sub-recommendations append their letter. Class IRI: http://smart.who.int/kg/recommendation."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* identifier 0..1 string "Identifier" "The published number (e.g. A.1.1); sub-recommendations append their letter."
* statement 0..1 markdown "Statement" "The recommendation, VERBATIM; the only stored copy."
* kind 0..1 code "Kind" "What sort of normative statement this is."
* kind from KGRecommendationKindVS (required)
* direction 0..1 code "Direction" "For or against."
* direction from KGRecommendationDirectionVS (required)
* strength 0..1 code "Strength" "GRADE strength."
* strength from KGRecommendationStrengthVS (required)
* overallCertainty 0..1 code "Overall certainty" "GRADE certainty of evidence."
* overallCertainty from KGCertaintyVS (required)
* justification 0..1 markdown "Justification" "The printed justification, verbatim."
* status 0..1 code "Status" "Whether a recommendation is still in force."
* status from KGRecommendationStatusVS (required)
* changeStatus 0..1 code "Change status" "Whether this edition of a consolidated guideline introduces, updates or carries a recommendation or indicator unchanged."
* changeStatus from KGChangeStatusVS (required)
* intervention 0..1 string "Intervention" "Verbatim slot: the intervention, quoted from the statement, a remark, caption or heading."
* interventionType 0..1 code "Intervention type" "DRAFT."
* interventionType from KGInterventionTypeVS (required)
* population 0..1 string "Population" "Verbatim slot: the population."
* setting 0..1 string "Setting" "Verbatim slot: the setting (absorbs the former conditionality)."
* provider 0..1 string "Provider" "Verbatim slot: who provides it."
* timing 0..1 string "Timing" "Verbatim slot: when."
* contentHash 0..1 string "Content hash" "sha256 of the normalised statement; unchanged on re-extraction means current."

Logical: KGRemark
Title: "Knowledge graph L1: Remark"
Description: "A remark attached to a recommendation (handbook §10.6). May also be printed as a table footnote. Class IRI: http://smart.who.int/kg/remark."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* text 0..1 markdown "Text" "The remark, verbatim."
* remarkType 0..1 code "Remark type" "What a remark is for."
* remarkType from KGRemarkTypeVS (required)
* ordinal 0..1 unsignedInt "Ordinal" "Position among the recommendation's remarks."
* contentHash 0..1 string "Content hash" "sha256 of the normalised text."

Logical: KGKeyQuestion
Title: "Knowledge graph L1: Key question"
Description: "A question in PICO format, framed before the evidence search (handbook §7.1–7.4). P and C are verbatim text with codes through crossReferences; I is also joined to a catalogued intervention; O is the outcome node. Class IRI: http://smart.who.int/kg/key-question."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* identifier 0..1 string "Identifier" "The question's published number."
* text 0..1 markdown "Text" "The question, verbatim."
* population 0..1 string "Population" "P, verbatim."
* intervention 0..1 string "Intervention" "I, verbatim."
* comparator 0..1 string "Comparator" "C, verbatim."
* setting 0..1 string "Setting" "Setting, verbatim."
* contentHash 0..1 string "Content hash" "sha256 of the normalised text."

Logical: KGOutcome
Title: "Knowledge graph L1: Outcome"
Description: "An outcome a guideline group chose to judge a key question by, with its importance in this guideline (handbook §7.6). A node because evidence attaches to it and one list is shared by several questions (ANC Web annex 1). Flat: one node per specific outcome. name as first printed; aliases are the other printed forms (e.g. 'EGWG'); category is the printed group heading (e.g. 'Fetal/newborn morbidity'). Class IRI: http://smart.who.int/kg/outcome."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* name 0..1 string "Name" "The outcome as first printed."
* importance 0..1 code "Importance" "How the guideline development group rated an outcome on the 1–9 scale: 7–9 critical, 4–6 important."
* importance from KGOutcomeImportanceVS (required)
* aliases 0..* string "Aliases" "Other printed forms of the outcome (e.g. 'EGWG')."
* category 0..1 string "Category" "The printed group heading (e.g. 'Fetal/newborn morbidity')."

Logical: KGEvidence
Title: "Knowledge graph L1: Evidence"
Description: "One row of an evidence profile: the evidence for one outcome of one key question, with its certainty (handbook §9.2). Class IRI: http://smart.who.int/kg/evidence."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* evidenceType 0..1 code "Evidence type" "Which kind of evidence a row is, and so which scale its certainty is on: GRADE for effects, GRADE-CERQual for qualitative findings."
* evidenceType from KGEvidenceTypeVS (required)
* certainty 0..1 code "Certainty" "GRADE certainty of evidence."
* certainty from KGCertaintyVS (required)
* summary 0..1 markdown "Summary" "Summary of the body of evidence."
* studyCount 0..1 unsignedInt "Study count" "Number of studies in the body of evidence."
* citation 0..1 string "Citation" "Bibliographic citation of the evidence review."
* contentHash 0..1 string "Content hash" "sha256 of the normalised summary."

Logical: KGHealthIntervention
Title: "Knowledge graph L1: Health intervention"
Description: "An intervention identified in a WHO catalogue or classification (UHC Compendium, ICHI, CDHI), digital interventions included. A peer of recommendation, not a recommendation. A DAK may draw on both. Corresponds to HealthInterventions: identifier and description correspond to HealthInterventions.id and description[x]; not a Parent because HealthInterventions requires reference 1..* DublinCore, which here is an edge (definedIn) rather than a field. Class IRI: http://smart.who.int/kg/health-intervention."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* identifier 0..1 string "Identifier" "The catalogue code (UHC, ICHI, CDHI)."
* name 0..1 string "Name" "Name, as catalogued."
* description 0..1 markdown "Description" "Description, as catalogued."
* interventionType 0..1 code "Intervention type" "DRAFT."
* interventionType from KGInterventionTypeVS (required)

Logical: KGIndicator
Title: "Knowledge graph L1: Indicator"
Description: "A WHO indicator, identified by its published reference number. Printed in several places (HIV SI 2022: summary list, Table 2.3, reference sheet) and stored once. variants is a list of {population, definition, numerator, denominator} for population-specific or level-specific forms (PRV.17, PRV.3). Corresponds to ProgramIndicator: definition, numerator, denominator and disaggregation are ProgramIndicator's elements and types (markdown); not a Parent because ProgramIndicator makes them 1..1 and an L1 indicator is recorded with what its source prints. Class IRI: http://smart.who.int/kg/indicator."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* refNo 0..1 string "Reference number" "The indicator's printed reference number (e.g. PRV.3)."
* shortName 0..1 string "Short name" "Short name, as printed."
* definition 0..1 markdown "Definition" "Definition, verbatim."
* numerator 0..1 markdown "Numerator" "Numerator, verbatim."
* denominator 0..1 markdown "Denominator" "Denominator, verbatim."
* variants 0..* BackboneElement "Variants" "Population- or level-specific forms (PRV.17, PRV.3)."
  * population 0..1 string "Population" "The population this variant is for."
  * definition 0..1 markdown "Definition" "Definition, verbatim."
  * numerator 0..1 markdown "Numerator" "Numerator, verbatim."
  * denominator 0..1 markdown "Denominator" "Denominator, verbatim."
* whatItMeasures 0..1 markdown "What it measures" "As printed."
* rationale 0..1 markdown "Rationale" "As printed."
* methodOfMeasurement 0..1 markdown "Method of measurement" "As printed."
* disaggregation 0..1 markdown "Disaggregation" "As printed."
* programmeArea 0..1 string "Programme area" "As printed."
* isCore 0..1 boolean "Is core" "Whether the publication marks it a core indicator."
* isSurveyBased 0..1 boolean "Is survey-based" "Whether it is measured by survey."
* changeStatus 0..1 code "Change status" "Whether this edition of a consolidated guideline introduces, updates or carries a recommendation or indicator unchanged."
* changeStatus from KGChangeStatusVS (required)
* contentHash 0..1 string "Content hash" "sha256 of the normalised definition, numerator and denominator."

Logical: KGCitation
Title: "Knowledge graph L1: Citation"
Description: "One citation string exactly as written in a DAK artefact. A cell holding several citations yields several nodes. Content-addressed in the DAK's namespace, so one string is one node across artefacts. Where a citation was found is recorded by appearsIn (L2) and by each use edge (L2-DMN, L3 citesSource), not on the node. Class IRI: http://smart.who.int/kg/citation."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* text 0..1 string "Text" "The citation string, VERBATIM, as written in the DAK artefact."
* numbering 0..1 string "Numbering" "The '(n)' back-reference into the artefact's reference list."
* citationKind 0..1 code "Citation kind" "Whether a citation string names a source, or stands in for one that is missing."
* citationKind from KGCitationKindVS (required)
* resolutionStatus 0..1 code "Resolution status" "Whether a citation string has been matched to what it cites."
* resolutionStatus from KGResolutionStatusVS (required)

Logical: KGReferenceEntry
Title: "Knowledge graph L1: Reference entry"
Description: "One row of a DAK artefact's own reference list: '(1)' and the full bibliographic text and URL it stands for. Resolved once; every citation numbered to it shares the result. Class IRI: http://smart.who.int/kg/reference-entry."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* number 0..1 string "Number" "The entry's number in the reference list."
* text 0..1 markdown "Text" "The full bibliographic text, verbatim."
* url 0..1 uri "URL" "The URL the entry prints."
* resolutionStatus 0..1 code "Resolution status" "Whether a citation string has been matched to what it cites."
* resolutionStatus from KGResolutionStatusVS (required)

Logical: KGTerminologyCode
Parent: Coding
Title: "Knowledge graph L1: Terminology code"
Description: "A code in an external terminology — ICD-10, ICD-11, SNOMED CT, ATC, or a WHO classification such as CDHI. CROSS-REFERENCE ONLY. It records system, code and display, and asserts NOTHING about the terminology: no hierarchy, no subsumption, no synonyms, no post-coordination. The terminology has its own authority, its own release cycle and its own tooling, and a partial copy here would be wrong within one release. Resolve meaning against the terminology server, not against this graph. Derives from Coding (FHIR R4 core datatype); system, code, display, version are its elements. Class IRI: http://smart.who.int/kg/terminology-code."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"

Logical: KGEvidenceLocation
Title: "Knowledge graph: evidence location"
Description: "Where a node or edge came from in its source. Required on anything not mechanically derived."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* location 1..1 string "Location" "file:line, a spreadsheet sheet and cell, or a BPMN element id."
* quote 0..1 string "Quote" "Verbatim text from the source."
* artifact 0..1 string "Artifact" "The generated artifact affected, where one exists."
* by 0..1 string "By" "Who made the judgement; required when derivation is decided."
* at 0..1 date "At" "When the judgement was made; required when derivation is decided."

Logical: KGProvenanceSource
Title: "Knowledge graph: provenance source"
Description: "A source a graph document was extracted from, pinned by hash."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* path 1..1 string "Path" "Path of the source."
* sha256 1..1 string "SHA-256" "Hash of the source (64 lower-case hex digits)."
* repository 0..1 string "Repository" "Repository holding the source."
* commit 0..1 string "Commit" "Commit the source was read at."
* note 0..1 string "Note" "What the hash covers, where that is not obvious."

Logical: KGNode
Title: "Knowledge graph: node"
Description: "One typed node of a knowledge-graph document. Its instance fields are an instance of the logical model of its class (see definedBy), e.g. KGPublication for a publication."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* id 1..1 string "ID" "IRI, unique within the document."
* type 1..1 code "Type" "The node's class."
* type from KGL1ClassesVS (extensible)
* label 1..1 string "Label" "Human-readable name. Required so a retrieved node reads without resolving it."
* definedBy 0..1 uri "Defined by" "Canonical URL of the logical model giving this node's instance shape."
* properties 0..1 BackboneElement "Properties" "Instance fields, as declared by the class's logical model."
* derivation 1..1 code "Derivation" "derived | inferred | decided."
* derivation from KGDerivationVS (required)
* note 0..1 string "Note" "Why it is what it is. Required unless derived."
* evidence 0..1 KGEvidenceLocation "Evidence" "Where it came from. Required unless derived."
* flagRef 0..1 string "Flag" "Id of a flag raised while extracting this node."
* skill 0..1 string "Skill" "Skill id that produced this node."

Logical: KGEdge
Title: "Knowledge graph: edge"
Description: "One reified statement: a predicate from a source node to a target node, with its derivation and evidence."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* type 1..1 code "Type" "Always Statement (rdf:Statement)."
* predicate 1..1 code "Predicate" "The predicate; the layer's edge table says which (source, target) pairs it licenses."
* predicate from KGL1PredicatesVS (extensible)
* source 1..1 string "Source" "IRI of the source node."
* target 1..1 string "Target" "IRI of the target node."
* qualifier 0..1 string "Qualifier" "A label on the relationship."
* derivation 1..1 code "Derivation" "derived | inferred | decided."
* derivation from KGDerivationVS (required)
* note 0..1 string "Note" "Why it is what it is. Required unless derived."
* evidence 0..1 KGEvidenceLocation "Evidence" "Where it came from. Required unless derived."
* flagRef 0..1 string "Flag" "Id of a flag raised while extracting this edge."
* skill 0..1 string "Skill" "Skill id that produced this edge."
* properties 0..1 BackboneElement "Properties" "Fields of the statement itself."
  * resolutionStatus 0..1 code "Resolution status" "For a cross-format join: unresolved | resolved | ambiguous."
  * resolutionStatus from KGResolutionStatusVS (required)
  * matchedOn 0..1 string "Matched on" "What the join was matched on."

Logical: KGGraphDocument
Title: "Knowledge graph L1: graph document"
Description: "One L1 knowledge-graph document: typed nodes and reified edges, provenance-pinned to the sources it was extracted from. In JSON the context element is written @context."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* context 1..1 uri "Context" "The JSON-LD context (written @context in JSON)."
* id 1..1 string "ID" "IRI of this graph document."
* type 1..1 code "Type" "Always Entity (prov:Entity)."
* ontologyVersion 1..1 string "Ontology version" "schemaVersion of the ontology this graph was built against."
* generatedAt 1..1 dateTime "Generated at" "When the document was generated."
* wasDerivedFrom 0..* KGProvenanceSource "Derived from" "The sources this graph was extracted from, each pinned by hash."
* nodes 0..* KGNode "Nodes" "The nodes."
* edges 0..* KGEdge "Edges" "The edges."
* dak 0..1 BackboneElement "DAK" "The DAK envelope: the fields of the DAK logical model."
