/**
 * FHIR Shorthand generated from the Zod schema — the bridge to the FHIR
 * toolchain.
 *
 * SUSHI compiles what this writes into StructureDefinitions (logical models),
 * CodeSystems and ValueSets; the IG Publisher renders them; and smart-base's
 * existing `input/scripts/generate_logical_model_schemas.py` and
 * `generate_valueset_schemas.py` turn those into JSON Schema and JSON-LD, as
 * they already do for every other logical model here. Nothing downstream needs
 * to know the source was Zod.
 *
 * What is generated:
 *  - one CodeSystem `<Name>` + all-codes ValueSet `<Name>VS` per closed code
 *    list (`vocab.ts`) — the `VS` suffix as `CoreDataElementTypeVS` has it,
 *    since SUSHI warns when the two share a name —
 *    plus one each for the layer's class ids and predicates;
 *  - one Logical model per ontology class, `KG<Class>`, whose elements are the
 *    class's typed properties — the instance shape a node's `definedBy`
 *    points at;
 *  - the document envelope: `KGGraphDocument`, `KGNode`, `KGEdge`,
 *    `KGEvidenceLocation`, `KGProvenanceSource` (not `KGEvidence`: that is the
 *    L1 class `evidence`, a body of evidence, not a pointer into a source).
 *
 * One deliberate difference from the JSON: FHIR element names cannot start
 * with `@`, so the document's `@context` is the element `context`. The JSON
 * Schema emitted from Zod keeps `@context`, and is the one a JSON document is
 * validated against.
 */
import type { ClassSpec, LayerSpec } from "./ontology.ts";
import { CODE_LISTS, type CodeList } from "./vocab.ts";

export const GENERATED_BANNER = (source: string) =>
  `// GENERATED by kg/src/emit.ts from ${source}. Do not edit: change the Zod source and run \`npm run build\` in kg/.`;

/** A FSH string literal. */
export function q(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\s*\n\s*/g, " ")}"`;
}

/** `publication-section` → `PublicationSection`. */
export function pascal(id: string): string {
  return id.replace(/(^|-)([a-z0-9])/g, (_m, _d, ch: string) => ch.toUpperCase());
}

export function classModelName(c: ClassSpec): string {
  return `KG${pascal(c.id)}`;
}

function codeSystem(l: CodeList): string {
  const out = [
    `CodeSystem: ${l.name}`,
    `Title: ${q(l.title)}`,
    `Description: ${q(`${l.description} Source: ${l.source}.`)}`,
    "",
    "* ^experimental = false",
    "* ^caseSensitive = true",
    "* ^status = #active",
    '* ^publisher = "World Health Organization (WHO)"',
    "",
    ...l.codes.map((c) => `* #${c.code} ${q(c.display)} ${q(c.definition)}`),
  ];
  return out.join("\n");
}

function valueSet(l: CodeList): string {
  return [
    `ValueSet: ${l.name}VS`,
    `Title: ${q(l.title)}`,
    `Description: ${q(`All codes of ${l.name}.`)}`,
    "",
    "* ^experimental = false",
    "* ^status = #active",
    '* ^publisher = "World Health Organization (WHO)"',
    `* include codes from system ${l.name}`,
  ].join("\n");
}

/** The layer's own vocabularies: its class ids and its predicates. */
export function layerCodeLists(l: LayerSpec): CodeList[] {
  const tag = l.layer.toUpperCase();
  return [
    {
      name: `KG${tag}Classes`,
      title: `Knowledge graph ${tag}: classes`,
      description: `The classes of the ${tag} layer of the SMART Guidelines knowledge graph. A node's \`type\` is one of these.`,
      source: `kg/src/${l.layer}.ts (migrated from smart-kg ontology/${l.layer}/${l.layer}.json)`,
      codes: l.classes.map((c) => ({ code: c.id, display: c.name, definition: c.note })),
    },
    {
      name: `KG${tag}Predicates`,
      title: `Knowledge graph ${tag}: predicates`,
      description: `The predicates of the ${tag} layer. An edge's \`predicate\` is one of these; which (source, target) pairs each licenses is the layer's edge table.`,
      source: `kg/src/${l.layer}.ts (migrated from smart-kg ontology/${l.layer}/${l.layer}.json)`,
      codes: l.predicates.map((p) => ({ code: p.predicate, display: p.predicate, definition: p.note })),
    },
  ];
}

function classModel(c: ClassSpec, layer: LayerSpec): string {
  const reuse = c.parent
    ? ` Derives from ${c.parent.name} (${c.parent.where}); ${Object.entries(c.properties).filter(([, p]) => p.inherited).map(([n]) => n).join(", ")} are its elements.`
    : c.correspondsTo
      ? ` Corresponds to ${c.correspondsTo.name}: ${c.correspondsTo.why}.`
      : "";
  const out = [
    `Logical: ${classModelName(c)}`,
    ...(c.parent ? [`Parent: ${c.parent.name}`] : []),
    `Title: ${q(`Knowledge graph ${layer.layer.toUpperCase()}: ${c.name}`)}`,
    `Description: ${q(`${c.note}${c.propertyNote ? ` ${c.propertyNote}` : ""}${reuse} Class IRI: ${c.iri}.`)}`,
    "",
    "* ^status = #active",
    '* ^publisher = "World Health Organization (WHO)"',
  ];
  for (const [name, p] of Object.entries(c.properties)) {
    if (p.inherited) continue;
    out.push(`* ${name} 0..${p.max ?? "1"} ${p.fhir} ${q(p.short)} ${q(p.definition)}`);
    if (p.binding) out.push(`* ${name} from ${p.binding.name}VS (required)`);
  }
  return out.join("\n");
}

function envelopeModels(l: LayerSpec): string {
  const tag = l.layer.toUpperCase();
  return `Logical: KGEvidenceLocation
Title: "Knowledge graph: evidence location"
Description: "Where a node or edge came from in its source. Required on anything not mechanically derived."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* location 1..1 string "Location" "file:line, a spreadsheet sheet and cell, or a BPMN element id."
* quote 0..1 string "Quote" "Verbatim text from the source."
* artifact 0..1 string "Artifact" "The generated artifact affected, where one exists."

Logical: KGProvenanceSource
Title: "Knowledge graph: provenance source"
Description: "A source a graph document was extracted from, pinned by hash."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* path 1..1 string "Path" "Path of the source."
* sha256 1..1 string "SHA-256" "Hash of the source (64 lower-case hex digits)."
* repository 0..1 string "Repository" "Repository holding the source."
* commit 0..1 string "Commit" "Commit the source was read at."
* note 0..1 string "Note" "What the hash covers, where that is not obvious."

Logical: KGNode
Title: "Knowledge graph: node"
Description: "One typed node of a knowledge-graph document. Its instance fields are an instance of the logical model of its class (see definedBy), e.g. KGPublication for a publication."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* id 1..1 string "ID" "IRI, unique within the document."
* type 1..1 code "Type" "The node's class."
* type from KG${tag}ClassesVS (required)
* label 1..1 string "Label" "Human-readable name. Required so a retrieved node reads without resolving it."
* definedBy 0..1 uri "Defined by" "Canonical URL of the logical model giving this node's instance shape."
* properties 0..1 BackboneElement "Properties" "Instance fields, as declared by the class's logical model."
* derivation 1..1 code "Derivation" "derived | inferred | decided."
* derivation from KGDerivationVS (required)
* note 0..1 string "Note" "Why it is what it is. Required unless derived."
* evidence 0..1 KGEvidenceLocation "Evidence" "Where it came from. Required unless derived."
* flagRef 0..1 string "Flag" "Id of a flag raised while extracting this node."
* skill 0..1 string "Skill" "Skill id that produced this node."

Logical: KGEdge
Title: "Knowledge graph: edge"
Description: "One reified statement: a predicate from a source node to a target node, with its derivation and evidence."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* type 1..1 code "Type" "Always Statement (rdf:Statement)."
* predicate 1..1 code "Predicate" "The predicate; the layer's edge table says which (source, target) pairs it licenses."
* predicate from KG${tag}PredicatesVS (required)
* source 1..1 string "Source" "IRI of the source node."
* target 1..1 string "Target" "IRI of the target node."
* qualifier 0..1 string "Qualifier" "A label on the relationship."
* derivation 1..1 code "Derivation" "derived | inferred | decided."
* derivation from KGDerivationVS (required)
* note 0..1 string "Note" "Why it is what it is. Required unless derived."
* evidence 0..1 KGEvidenceLocation "Evidence" "Where it came from. Required unless derived."
* flagRef 0..1 string "Flag" "Id of a flag raised while extracting this edge."
* skill 0..1 string "Skill" "Skill id that produced this edge."
* properties 0..1 BackboneElement "Properties" "Fields of the statement itself."
  * resolutionStatus 0..1 code "Resolution status" "For a cross-format join: unresolved | resolved | ambiguous."
  * resolutionStatus from KGResolutionStatusVS (required)
  * matchedOn 0..1 string "Matched on" "What the join was matched on."

Logical: KGGraphDocument
Title: "Knowledge graph ${tag}: graph document"
Description: "One ${tag} knowledge-graph document: typed nodes and reified edges, provenance-pinned to the sources it was extracted from. In JSON the context element is written @context."

* ^status = #active
* ^publisher = "World Health Organization (WHO)"
* context 1..1 uri "Context" "The JSON-LD context (written @context in JSON)."
* id 1..1 string "ID" "IRI of this graph document."
* type 1..1 code "Type" "Always Entity (prov:Entity)."
* ontologyVersion 1..1 string "Ontology version" "schemaVersion of the ontology this graph was built against."
* generatedAt 1..1 dateTime "Generated at" "When the document was generated."
* wasDerivedFrom 0..* KGProvenanceSource "Derived from" "The sources this graph was extracted from, each pinned by hash."
* nodes 0..* KGNode "Nodes" "The nodes."
* edges 0..* KGEdge "Edges" "The edges."
* dak 0..1 BackboneElement "DAK" "The DAK envelope: the fields of the DAK logical model."`;
}

export interface FshFile {
  /** Path relative to the smart-base repository root. */
  path: string;
  text: string;
}

export function fshFiles(layer: LayerSpec, source: string): FshFile[] {
  const banner = GENERATED_BANNER(source);
  const lists = [...CODE_LISTS, ...layerCodeLists(layer)];
  const files: FshFile[] = [];
  for (const l of lists) {
    files.push({ path: `input/fsh/codesystems/${l.name}.fsh`, text: `${banner}\n${codeSystem(l)}\n` });
    files.push({ path: `input/fsh/valuesets/${l.name}VS.fsh`, text: `${banner}\n${valueSet(l)}\n` });
  }
  const models = [...layer.classes.map((c) => classModel(c, layer)), envelopeModels(layer)].join("\n\n");
  files.push({ path: `input/fsh/models/KG${layer.layer.toUpperCase()}.fsh`, text: `${banner}\n${models}\n` });
  return files;
}
